version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - docker-login
          filters:
            branches:
              only:
                - main
                - restore-k8s
jobs:
  build:
    docker:
      - image: 'circleci/node:22.7.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install
          command: |
            npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            mkdir dist
            mkdir dist/moneymaker-client
            export NODE_OPTIONS=--openssl-legacy-provider
            npm run build-prod
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export IMAGE_NAME=moneymaker-client' >> $BASH_ENV
            echo 'export DOCKER_REPOSITORY=trance0302' >> $BASH_ENV
      - setup_remote_docker:
          version: docker23
      - run:
          name: Update version
          command: |
            npm run semantic-release || true
      - run:
          name: Build and Push Image
          command: |
            bash docker_build_push.sh $DOCKER_REPOSITORY/$IMAGE_NAME $DOCKER_USERNAME $DOCKER_PWD
